
version: '3.8'

services:
  api:
    image: ${IMAGE_NAME:-ghcr.io/khadiza13/mlops_fastapi_poc/titanic-api:latest}
    container_name: titanic-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - titanic-network

networks:
  titanic-network:
    driver: bridge