name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Match ci.yml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest great_expectations
      - name: Lint, test, and validate
        run: |
          flake8 --max-line-length=88 .
          black --check .
          pytest tests/
      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/titanic-api:latest .
          docker push ghcr.io/${{ github.repository }}/titanic-api:latest
      - name: Redeploy using Docker Compose
        run: |
          docker-compose pull # Use docker-compose if needed
          docker-compose up -d
      - name: Trigger retraining
        run: |
          python train.py # Adjusted path based on your structure
        env:
          PYTHONPATH: ${{ github.workspace }}