name: CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest great_expectations
      - name: Lint, test, and validate
        run: |
          flake8 --max-line-length=88 .
          black --check .
          pytest tests/
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/titanic-api:latest .
          docker push ghcr.io/${{ github.repository }}/titanic-api:latest
      - name: Redeploy on self-hosted runner
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /path/to/deployment
            docker compose pull
            docker compose up -d