name: CI

on:
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest great_expectations

      - name: Lint with flake8
        run: flake8 --max-line-length=88 .

      - name: Format check with black
        run: black --check .

      - name: Run unit and data validation tests
        run: pytest tests/

      - name: Build Docker image
        run: docker build -t titanic-api .